[package]
name = "vocal_mouse"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.15.3"
anyhow = "1.0"
pitch-detector = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
enigo = { version = "0.3.0", features = ["wayland"] }
device_query = "3.0.1"
